// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSelene;

#nullable disable

namespace ProjectSelene.Migrations
{
    [DbContext(typeof(SeleneDbContext))]
    [Migration("20230711081232_SwitchToSQLite")]
    partial class SwitchToSQLite
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("ProjectSelene.Models.Mod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatestVersionNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("ProjectSelene.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GithubId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectSelene.Models.Mod", b =>
                {
                    b.HasOne("ProjectSelene.Models.User", "Author")
                        .WithMany("Mods")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ProjectSelene.Models.ModInfo", "Info", b1 =>
                        {
                            b1.Property<int>("ModId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("ModId");

                            b1.ToTable("Mods");

                            b1.WithOwner()
                                .HasForeignKey("ModId");
                        });

                    b.OwnsMany("ProjectSelene.Models.ModVersion", "Versions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("OwnedById")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("SubmittedById")
                                .HasColumnType("INTEGER");

                            b1.Property<DateTime>("SubmittedOn")
                                .HasColumnType("TEXT");

                            b1.Property<int?>("VerifiedById")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Version")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("OwnedById");

                            b1.HasIndex("SubmittedById");

                            b1.HasIndex("VerifiedById");

                            b1.ToTable("ModVersion");

                            b1.WithOwner("OwnedBy")
                                .HasForeignKey("OwnedById");

                            b1.HasOne("ProjectSelene.Models.User", "SubmittedBy")
                                .WithMany()
                                .HasForeignKey("SubmittedById")
                                .OnDelete(DeleteBehavior.Cascade)
                                .IsRequired();

                            b1.HasOne("ProjectSelene.Models.User", "VerifiedBy")
                                .WithMany()
                                .HasForeignKey("VerifiedById");

                            b1.OwnsMany("ProjectSelene.Models.Artifact", "Artifacts", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("INTEGER");

                                    b2.Property<int>("ModVersionId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("Url")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ModVersionId");

                                    b2.ToTable("Artifact");

                                    b2.WithOwner()
                                        .HasForeignKey("ModVersionId");
                                });

                            b1.Navigation("Artifacts");

                            b1.Navigation("OwnedBy");

                            b1.Navigation("SubmittedBy");

                            b1.Navigation("VerifiedBy");
                        });

                    b.Navigation("Author");

                    b.Navigation("Info")
                        .IsRequired();

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ProjectSelene.Models.User", b =>
                {
                    b.Navigation("Mods");
                });
#pragma warning restore 612, 618
        }
    }
}
