// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectSelene;

#nullable disable

namespace ProjectSelene.Migrations
{
    [DbContext(typeof(SeleneDbContext))]
    [Migration("20240501182051_BreakCycles")]
    partial class BreakCycles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("ProjectSelene.Models.Artifact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ModVersionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StoredObjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ModVersionId");

                    b.HasIndex("StoredObjectId");

                    b.ToTable("Artifact");
                });

            modelBuilder.Entity("ProjectSelene.Models.Mod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("Guid")
                        .HasColumnType("TEXT");

                    b.Property<int>("ModInfoId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasAlternateKey("Guid");

                    b.HasIndex("AuthorId");

                    b.HasIndex("ModInfoId")
                        .IsUnique();

                    b.ToTable("Mods");
                });

            modelBuilder.Entity("ProjectSelene.Models.ModInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ModInfo");
                });

            modelBuilder.Entity("ProjectSelene.Models.ModVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DownloadId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OwnedById")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubmittedById")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SubmittedOn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VerifiedById")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DownloadId");

                    b.HasIndex("OwnedById");

                    b.HasIndex("SubmittedById");

                    b.HasIndex("VerifiedById");

                    b.ToTable("ModVersion");
                });

            modelBuilder.Entity("ProjectSelene.Models.StoredObject", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("StoredObjects");
                });

            modelBuilder.Entity("ProjectSelene.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("DiscordId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GithubId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DiscordId");

                    b.HasIndex("GithubId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectSelene.Models.Artifact", b =>
                {
                    b.HasOne("ProjectSelene.Models.ModVersion", "ModVersion")
                        .WithMany("Artifacts")
                        .HasForeignKey("ModVersionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("ProjectSelene.Models.StoredObject", "StoredObject")
                        .WithMany("Artifacts")
                        .HasForeignKey("StoredObjectId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ModVersion");

                    b.Navigation("StoredObject");
                });

            modelBuilder.Entity("ProjectSelene.Models.Mod", b =>
                {
                    b.HasOne("ProjectSelene.Models.User", "Author")
                        .WithMany("Mods")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSelene.Models.ModInfo", "Info")
                        .WithOne()
                        .HasForeignKey("ProjectSelene.Models.Mod", "ModInfoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Info");
                });

            modelBuilder.Entity("ProjectSelene.Models.ModVersion", b =>
                {
                    b.HasOne("ProjectSelene.Models.Artifact", "Download")
                        .WithMany("DownloadModVersions")
                        .HasForeignKey("DownloadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSelene.Models.Mod", "OwnedBy")
                        .WithMany("Versions")
                        .HasForeignKey("OwnedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSelene.Models.User", "SubmittedBy")
                        .WithMany()
                        .HasForeignKey("SubmittedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectSelene.Models.User", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById");

                    b.Navigation("Download");

                    b.Navigation("OwnedBy");

                    b.Navigation("SubmittedBy");

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("ProjectSelene.Models.StoredObject", b =>
                {
                    b.HasOne("ProjectSelene.Models.User", "Owner")
                        .WithMany("StoredObjects")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ProjectSelene.Models.Artifact", b =>
                {
                    b.Navigation("DownloadModVersions");
                });

            modelBuilder.Entity("ProjectSelene.Models.Mod", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("ProjectSelene.Models.ModVersion", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("ProjectSelene.Models.StoredObject", b =>
                {
                    b.Navigation("Artifacts");
                });

            modelBuilder.Entity("ProjectSelene.Models.User", b =>
                {
                    b.Navigation("Mods");

                    b.Navigation("StoredObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
