name: Publish
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/project-selene/project-selene:latest
  publish-main:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Kubernetes context
      uses: Azure/k8s-set-context@v4
      with:
        method: service-account
        k8s-url: ${{ secrets.K8S_URL }}
        k8s-secret: ${{ secrets.K8S_SECRET }}
    - name: Deploy
      run: kubectl rollout restart deployment selene -n selene

  # publish-api:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - name: Checkout
  #     uses: actions/checkout@v3
  #     with:
  #       submodules: true
    
  #   - name: Setup node
  #     uses: actions/setup-node@v3
  #     with:
  #       node-version: 20.x
  #       cache: npm
  #       registry-url: 'https://registry.npmjs.org'
  #       cache-dependency-path: ProjectSelene.Modloader.API/package-lock.json

  #   - name: Setup dependencies
  #     run: npm ci
  #     working-directory: ProjectSelene.Modloader.API
    
  #   - name: Publish
  #     run: npm publish
  #     working-directory: ProjectSelene.Modloader.API
  #     env:
  #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
  #     continue-on-error: true